// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package nbchat.message;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResponseMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string chatRoom = 1;
    java.util.List<String> getChatRoomList();
    int getChatRoomCount();
    String getChatRoom(int index);
  }
  public static final class ResponseMessage extends
      com.google.protobuf.GeneratedMessage
      implements ResponseMessageOrBuilder {
    // Use ResponseMessage.newBuilder() to construct.
    private ResponseMessage(Builder builder) {
      super(builder);
    }
    private ResponseMessage(boolean noInit) {}
    
    private static final ResponseMessage defaultInstance;
    public static ResponseMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResponseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nbchat.message.Chat.internal_static_nbserver_message_ResponseMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nbchat.message.Chat.internal_static_nbserver_message_ResponseMessage_fieldAccessorTable;
    }
    
    // repeated string chatRoom = 1;
    public static final int CHATROOM_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList chatRoom_;
    public java.util.List<String>
        getChatRoomList() {
      return chatRoom_;
    }
    public int getChatRoomCount() {
      return chatRoom_.size();
    }
    public String getChatRoom(int index) {
      return chatRoom_.get(index);
    }
    
    private void initFields() {
      chatRoom_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < chatRoom_.size(); i++) {
        output.writeBytes(1, chatRoom_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < chatRoom_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(chatRoom_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getChatRoomList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nbchat.message.Chat.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nbchat.message.Chat.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nbchat.message.Chat.ResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nbchat.message.Chat.ResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nbchat.message.Chat.ResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nbchat.message.Chat.ResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nbchat.message.Chat.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nbchat.message.Chat.ResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nbchat.message.Chat.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nbchat.message.Chat.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nbchat.message.Chat.ResponseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nbchat.message.Chat.ResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nbchat.message.Chat.internal_static_nbserver_message_ResponseMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nbchat.message.Chat.internal_static_nbserver_message_ResponseMessage_fieldAccessorTable;
      }
      
      // Construct using nbchat.message.Chat.ResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        chatRoom_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nbchat.message.Chat.ResponseMessage.getDescriptor();
      }
      
      public nbchat.message.Chat.ResponseMessage getDefaultInstanceForType() {
        return nbchat.message.Chat.ResponseMessage.getDefaultInstance();
      }
      
      public nbchat.message.Chat.ResponseMessage build() {
        nbchat.message.Chat.ResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nbchat.message.Chat.ResponseMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nbchat.message.Chat.ResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nbchat.message.Chat.ResponseMessage buildPartial() {
        nbchat.message.Chat.ResponseMessage result = new nbchat.message.Chat.ResponseMessage(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          chatRoom_ = new com.google.protobuf.UnmodifiableLazyStringList(
              chatRoom_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chatRoom_ = chatRoom_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nbchat.message.Chat.ResponseMessage) {
          return mergeFrom((nbchat.message.Chat.ResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nbchat.message.Chat.ResponseMessage other) {
        if (other == nbchat.message.Chat.ResponseMessage.getDefaultInstance()) return this;
        if (!other.chatRoom_.isEmpty()) {
          if (chatRoom_.isEmpty()) {
            chatRoom_ = other.chatRoom_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChatRoomIsMutable();
            chatRoom_.addAll(other.chatRoom_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureChatRoomIsMutable();
              chatRoom_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string chatRoom = 1;
      private com.google.protobuf.LazyStringList chatRoom_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureChatRoomIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          chatRoom_ = new com.google.protobuf.LazyStringArrayList(chatRoom_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getChatRoomList() {
        return java.util.Collections.unmodifiableList(chatRoom_);
      }
      public int getChatRoomCount() {
        return chatRoom_.size();
      }
      public String getChatRoom(int index) {
        return chatRoom_.get(index);
      }
      public Builder setChatRoom(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChatRoomIsMutable();
        chatRoom_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addChatRoom(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChatRoomIsMutable();
        chatRoom_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllChatRoom(
          java.lang.Iterable<String> values) {
        ensureChatRoomIsMutable();
        super.addAll(values, chatRoom_);
        onChanged();
        return this;
      }
      public Builder clearChatRoom() {
        chatRoom_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addChatRoom(com.google.protobuf.ByteString value) {
        ensureChatRoomIsMutable();
        chatRoom_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:nbserver.message.ResponseMessage)
    }
    
    static {
      defaultInstance = new ResponseMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nbserver.message.ResponseMessage)
  }
  
  public interface RequestMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .nbserver.message.RequestMessage.Type type = 1;
    boolean hasType();
    nbchat.message.Chat.RequestMessage.Type getType();
    
    // optional string userName = 2;
    boolean hasUserName();
    String getUserName();
  }
  public static final class RequestMessage extends
      com.google.protobuf.GeneratedMessage
      implements RequestMessageOrBuilder {
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(Builder builder) {
      super(builder);
    }
    private RequestMessage(boolean noInit) {}
    
    private static final RequestMessage defaultInstance;
    public static RequestMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nbchat.message.Chat.internal_static_nbserver_message_RequestMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nbchat.message.Chat.internal_static_nbserver_message_RequestMessage_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      GET_ROOMS(0, 0),
      ;
      
      public static final int GET_ROOMS_VALUE = 0;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return GET_ROOMS;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return nbchat.message.Chat.RequestMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        GET_ROOMS, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:nbserver.message.RequestMessage.Type)
    }
    
    private int bitField0_;
    // required .nbserver.message.RequestMessage.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private nbchat.message.Chat.RequestMessage.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public nbchat.message.Chat.RequestMessage.Type getType() {
      return type_;
    }
    
    // optional string userName = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.Object userName_;
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = nbchat.message.Chat.RequestMessage.Type.GET_ROOMS;
      userName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static nbchat.message.Chat.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nbchat.message.Chat.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nbchat.message.Chat.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static nbchat.message.Chat.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static nbchat.message.Chat.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nbchat.message.Chat.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static nbchat.message.Chat.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nbchat.message.Chat.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static nbchat.message.Chat.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static nbchat.message.Chat.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(nbchat.message.Chat.RequestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements nbchat.message.Chat.RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nbchat.message.Chat.internal_static_nbserver_message_RequestMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nbchat.message.Chat.internal_static_nbserver_message_RequestMessage_fieldAccessorTable;
      }
      
      // Construct using nbchat.message.Chat.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = nbchat.message.Chat.RequestMessage.Type.GET_ROOMS;
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nbchat.message.Chat.RequestMessage.getDescriptor();
      }
      
      public nbchat.message.Chat.RequestMessage getDefaultInstanceForType() {
        return nbchat.message.Chat.RequestMessage.getDefaultInstance();
      }
      
      public nbchat.message.Chat.RequestMessage build() {
        nbchat.message.Chat.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private nbchat.message.Chat.RequestMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        nbchat.message.Chat.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public nbchat.message.Chat.RequestMessage buildPartial() {
        nbchat.message.Chat.RequestMessage result = new nbchat.message.Chat.RequestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nbchat.message.Chat.RequestMessage) {
          return mergeFrom((nbchat.message.Chat.RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(nbchat.message.Chat.RequestMessage other) {
        if (other == nbchat.message.Chat.RequestMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasUserName()) {
          setUserName(other.getUserName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              nbchat.message.Chat.RequestMessage.Type value = nbchat.message.Chat.RequestMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .nbserver.message.RequestMessage.Type type = 1;
      private nbchat.message.Chat.RequestMessage.Type type_ = nbchat.message.Chat.RequestMessage.Type.GET_ROOMS;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public nbchat.message.Chat.RequestMessage.Type getType() {
        return type_;
      }
      public Builder setType(nbchat.message.Chat.RequestMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = nbchat.message.Chat.RequestMessage.Type.GET_ROOMS;
        onChanged();
        return this;
      }
      
      // optional string userName = 2;
      private java.lang.Object userName_ = "";
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      void setUserName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:nbserver.message.RequestMessage)
    }
    
    static {
      defaultInstance = new RequestMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nbserver.message.RequestMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nbserver_message_ResponseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nbserver_message_ResponseMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nbserver_message_RequestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nbserver_message_RequestMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\020nbserver.message\"#\n\017Res" +
      "ponseMessage\022\020\n\010chatRoom\030\001 \003(\t\"n\n\016Reques" +
      "tMessage\0223\n\004type\030\001 \002(\0162%.nbserver.messag" +
      "e.RequestMessage.Type\022\020\n\010userName\030\002 \001(\t\"" +
      "\025\n\004Type\022\r\n\tGET_ROOMS\020\000B\026\n\016nbchat.message" +
      "B\004Chat"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_nbserver_message_ResponseMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_nbserver_message_ResponseMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nbserver_message_ResponseMessage_descriptor,
              new java.lang.String[] { "ChatRoom", },
              nbchat.message.Chat.ResponseMessage.class,
              nbchat.message.Chat.ResponseMessage.Builder.class);
          internal_static_nbserver_message_RequestMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_nbserver_message_RequestMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nbserver_message_RequestMessage_descriptor,
              new java.lang.String[] { "Type", "UserName", },
              nbchat.message.Chat.RequestMessage.class,
              nbchat.message.Chat.RequestMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
